networks:
  proxy:
    external: true

services:
  stirlingpdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirlingpdf
    volumes:
      - ./data:/configs
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirlingpdf.entrypoints=https"
      - "traefik.http.routers.stirlingpdf.rule=Host(`pdf.server.example.com`)"
      - "traefik.http.routers.stirlingpdf.tls=true"
      - "traefik.http.routers.stirlingpdf.service=stirlingpdf"
      - "traefik.http.services.stirlingpdf.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
