services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - ./shows:/data/tvshows
      - ./movies:/data/movies
    restart: unless-stopped
    network_mode: "container:gluetun"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.entrypoints=http, https"
      - "traefik.http.routers.emby.rule=Host(`emby.server.example.com`)"
      - "traefik.http.routers.emby.tls=true"
      - "traefik.http.routers.emby.service=emby"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
      - "traefik.docker.network=proxy"
