services:
  nginx:
    image: nginxmod:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      HOST_HOSTNAME: "Germany Server"  
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

