services:
  ts-test:
    image: tailscale/tailscale:latest
    container_name: ts-test
    hostname: ts-test
    environment:
      - TS_AUTHKEY=<paste-oauth-key-here>?ephemeral=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - ./state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    configs:
      - source: ts-serve
        target: /config/serve.json

  nginx:
    image: nginx
    network_mode: "service:ts-test"
