networks:
  proxy:
    external: true

services:
  copyparty:
    image: copyparty/ac:latest
    user: "1000"
    container_name: copyparty
    restart: unless-stopped
    command:
      - "--rproxy"
      - "1"
      - "--xff-src=172.16.0.0/12"
    volumes:
      - ./stuff:/w
      - ./config:/cfg
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.copyparty.entrypoints=https"
      - "traefik.http.routers.copyparty.rule=Host(`cp.server.example.com`)"
      - "traefik.http.routers.copyparty.tls=true"
      - "traefik.http.routers.copyparty.service=copyparty"
      - "traefik.http.services.copyparty.loadbalancer.server.port=3923"
      - "traefik.docker.network=proxy"
